wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    start_time: 1747116320
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 1
      - 2
      - 13
      - 16
      4: 3.6.10
      5: 0.12.21
      8:
      - 5
batch_size:
  desc: null
  value: 150
emb_dim:
  desc: null
  value: 300
history_length:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 10
snapshot_weeks:
  desc: null
  value: 6
snapshots_num:
  desc: null
  value: 2016
